# Generated by Django 4.0.6 on 2022-07-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_image'),
        ('product', '0005_review_alter_image_product_delete_comment'),
    ]

    operations = [
    ]
