# Generated by Django 4.0.6 on 2022-07-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_merge_20220728_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
